import { START_ID, STEP_PREFIX, isStep, isOverlay, isSentinel, isPlaceholder, normaliseArr, VALID_TYPES, stepHeight } from './constants.js';

/**
 * Parses a flow-graph JSON string and derives the logical structure needed to
 * reconstruct the Cytoscape graph:
 *   - rules       : normalised flow rules
 *   - entry       : Set of entry tool names
 *   - stepGroups  : [{stepId, tools}] — one group per Cytoscape step node
 *   - toolToStepId: Map<toolName, stepId>
 *
 * Pure function — does NOT touch the Cytoscape instance.
 *
 * @param {string} json
 * @returns {{ rules, entry, stepGroups, toolToStepId }}
 * @throws if json is not valid JSON
 */
export function parseFlowJson(json) {
    const g = JSON.parse(json);
    const flow = g.flow || [];

    // Normalise rules; strip any rule that has no from or to
    const rules = flow
        .map((rule) => ({
            froms: normaliseArr(rule.fromTools ?? rule.from),
            tos: normaliseArr(rule.toTools ?? rule.to),
            type: VALID_TYPES.has(rule.type) ? rule.type : 'sequential',
            conditions: rule.conditions || {}
        }))
        .filter((r) => r.froms.length > 0 && r.tos.length > 0);

    // Collect every tool name appearing in the graph
    const allNames = new Set();
    for (const r of rules) {
        r.froms.forEach((n) => allNames.add(n));
        r.tos.forEach((n) => allNames.add(n));
    }

    // Derive entry tools: prefer explicit field, else topology (tools in 'from' but never 'to')
    const explicitEntry = new Set(g.entry || []);
    let entry;
    if (explicitEntry.size > 0) {
        entry = explicitEntry;
    } else {
        const allFrom = new Set(rules.flatMap((r) => r.froms));
        const allTo = new Set(rules.flatMap((r) => r.tos));
        const derived = [...allFrom].filter((t) => !allTo.has(t));
        entry = new Set(derived.length > 0 ? derived : [...allNames].slice(0, 1));
    }

    // ── Union-Find: group tools that belong in the SAME Step node ─────────
    // • Multiple fromTools in one rule → ran together (parallel step)
    // • Multiple toTools in a sequential/parallel rule → land in the same step
    // • toTools of an EXCLUSIVE rule → each goes to its own separate step
    const parent = new Map();
    for (const n of allNames) parent.set(n, n);

    const find = (n) => {
        if (parent.get(n) !== n) parent.set(n, find(parent.get(n)));
        return parent.get(n);
    };
    const union = (a, b) => {
        const pa = find(a);
        const pb = find(b);
        if (pa !== pb) parent.set(pa, pb);
    };

    for (const r of rules) {
        for (let i = 1; i < r.froms.length; i++) union(r.froms[0], r.froms[i]);
        if (r.type !== 'exclusive') {
            for (let i = 1; i < r.tos.length; i++) union(r.tos[0], r.tos[i]);
        }
    }

    // Build groups indexed by canonical representative
    const groupMap = new Map();
    for (const n of allNames) {
        const gk = find(n);
        if (!groupMap.has(gk)) groupMap.set(gk, []);
        groupMap.get(gk).push(n);
    }

    // Convert to a stable, sorted list of { stepId, tools } objects
    const stepGroups = [];
    const toolToStepId = new Map();
    for (const [, tools] of groupMap) {
        tools.sort();
        // Slugify the representative tool name so special characters don't produce
        // invalid Cytoscape IDs or broken CSS selectors.
        const safeKey = tools[0].replace(/[^a-zA-Z0-9_-]/g, '_');
        const stepId = `${STEP_PREFIX}${safeKey}`;
        for (const t of tools) toolToStepId.set(t, stepId);
        stepGroups.push({ stepId, tools });
    }

    return { rules, entry, stepGroups, toolToStepId };
}

/**
 * For every source node that has ≥2 exclusive outgoing edges, fills in any
 * blank conditions with generated defaults ("Condition 1", …, "Default condition"
 * for the last one).  This handles graphs generated by the LLM without conditions.
 *
 * Mutates the Cytoscape instance directly.
 *
 * @param {object} cy - Cytoscape instance
 */
export function applyFallbackConditions(cy) {
    const sourcesWithExclusive = new Set();
    cy.edges('[type="exclusive"]').forEach((e) => sourcesWithExclusive.add(e.data('source')));

    sourcesWithExclusive.forEach((srcId) => {
        const outExcl = cy.getElementById(srcId).outgoers('edge[type="exclusive"]');
        if (outExcl.length < 2) return;

        // Collect only the blank edges so the index and "Default condition" label
        // are computed relative to the blank-edge count, not the total edge count.
        const blanks = outExcl.filter((e) => !(e.data('condition') || '').trim());
        if (blanks.length === 0) return;

        let idx = 1;
        blanks.forEach((e) => {
            const isLast = idx === blanks.length;
            e.data('condition', isLast ? 'Default condition' : `Condition ${idx}`);
            idx++;
        });
    });
}

/**
 * Serialises the current Cytoscape graph state to the canonical flow-graph
 * JSON format (version 3.0).
 *
 * @param {object}      cy               - Cytoscape instance
 * @param {string|null} capabilitiesHash - optional hash to embed in the output
 * @returns {string} Pretty-printed JSON
 */
export function buildFlowJson(cy, capabilitiesHash) {
    const ruleMap = new Map();

    cy.edges().forEach((e) => {
        const srcId = e.data('source');
        const tgtId = e.data('target');
        if (isOverlay(srcId) || isOverlay(tgtId)) return;
        if (!isStep(srcId) || !isStep(tgtId)) return;

        const srcNode = cy.getElementById(srcId);
        const tgtNode = cy.getElementById(tgtId);
        const fromTools = JSON.parse(srcNode.data('tools') || '[]');
        const toTools = JSON.parse(tgtNode.data('tools') || '[]');
        const edgeType = e.data('type') || 'sequential';

        if (edgeType === 'exclusive') {
            const key = `${srcId}::exclusive`;
            if (!ruleMap.has(key)) {
                ruleMap.set(key, { fromTools, type: 'exclusive', toTools: [], conditions: {} });
            }
            const rule = ruleMap.get(key);
            const cond = e.data('condition') || '';
            toTools.forEach((t) => {
                if (!rule.toTools.includes(t)) rule.toTools.push(t);
                if (cond) rule.conditions[t] = cond;
            });
        } else {
            const type = toTools.length > 1 ? 'parallel' : edgeType;
            ruleMap.set(`${srcId}-->${tgtId}::${type}`, { fromTools, type, toTools });
        }
    });

    const flow = [...ruleMap.values()].map((r) => {
        // Omit the 'conditions' key when it is empty to keep the JSON tidy
        if (r.conditions && Object.keys(r.conditions).length === 0) {
            const { conditions, ...rest } = r; // eslint-disable-line no-unused-vars
            return rest;
        }
        return r;
    });

    // Derive entry tools from Start-node outgoing edges
    const entry = [];
    const seen = new Set();
    const startedStepIds = new Set();

    cy.edges(`[source="${START_ID}"]`).forEach((e) => {
        const targetId = e.data('target');
        if (!isStep(targetId)) return;
        startedStepIds.add(targetId);
        JSON.parse(cy.getElementById(targetId).data('tools') || '[]').forEach((t) => {
            if (!seen.has(t)) {
                seen.add(t);
                entry.push(t);
            }
        });
    });

    // Also include disconnected roots (no incoming step edge) as entry points
    cy.nodes('[nodeType="step"]').forEach((n) => {
        if (startedStepIds.has(n.id())) return;
        const hasIncomingStep = n.incomers('edge').filter((e) => isStep(e.data('source'))).length > 0;
        if (hasIncomingStep) return;
        JSON.parse(n.data('tools') || '[]').forEach((t) => {
            if (!seen.has(t)) {
                seen.add(t);
                entry.push(t);
            }
        });
    });

    const out = { version: '3.0', entry, flow };
    if (capabilitiesHash) out.capabilitiesHash = capabilitiesHash;
    return JSON.stringify(out, null, 2);
}
